owner: ggardin
repo: uptime-monitor
sites:
  - name: Giovanni Gardin
    url: https://www.giovannigardin.com
  - name: Ristorante Gelateria All'Angelo Da Lalo
    url: $SITE_RSTRLL
  - name: Life
    url: $SITE_LF
  #- name: Life CRM
  #  url: $SITE_LFCRM
  - name: Barchessa Loredan
    url: $SITE_BRKLRD
  - name: Confraternita Vini Asolo Montello
    url: $SITE_CVAM
  - name: Contemporanea
    url: $SITE_CNTM
  - name: Contemporanea B2B
    url: $SITE_CNTMB
  - name: Contemporanea Group
    url: $SITE_CNTMG
  - name: Montello Country House
    url: $SITE_MCH
  - name: ProSetup
    url: $SITE_PRSTP
  #- name: Sikrea
  #  url: $SITE_SKR
  - name: UNIPav
    url: $SITE_NPVBRT
  - name: Ekphrasis
    url: $SITE_KPHRS
  - name: Itaca Gallery
    url: $SITE_TCGLR
  - name: Punto Infissi
    url: $SITE_PTNFS
  #- name: Liquorificio Benedetti
  #  url: $SITE_BNDTLQ
  - name: Fabio Favrin portfolio
    url: $SITE_FLF

assignees:
  - ggardin

status-website:
  cname: status.giovannigardin.com
  logoUrl: https://raw.githubusercontent.com/ggardin/uptime-monitor/master/assets/gio-icon.svg
  name: Monitor
  introTitle: "**Stato** dei servizi web"
  introMessage: Vengono impiegate numerose tecnologie di ridondanza per garantire prestazioni e affidabilità ottimali. Tuttavia, qualora compaia un problema tecnico, pensiamo che i nostri clienti meritino una comunicazione chiara e trasparente. Su questa pagina è disponibile il monitoraggio dello stato dei servizi web.
  navbar:
    - title: Status
      href: /
  theme: light
  favicon: https://raw.githubusercontent.com/ggardin/uptime-monitor/master/assets/icon.png

i18n:
  activeIncidents: Incidenti attivi
  allSystemsOperational: Tutti i servizi sono operativi
  incidentReport: "Incident #$NUMBER report →"
  activeIncidentSummary: Aperto $DATE con $POSTS post
  incidentTitle: Report incidente $NUMBER
  incidentDetails: Dettagli incidente
  incidentFixed: Risolto
  incidentOngoing: In corso
  incidentOpenedAt: Aperto
  incidentClosedAt: Chiuso
  incidentSubscribe: Ricevi gli aggiornamenti
  incidentViewOnGitHub: Vedi su GitHub
  incidentCommentSummary: Pubblicato in data $DATE da $AUTHOR
  incidentBack: ← Torna agli incidenti
  pastIncidents: Incidenti passati
  pastIncidentsResolved: Risolto in $MINUTES minuti con $POSTS post
  liveStatus: Stato in tempo reale
  overallUptime: "Uptime complessivo: $UPTIME"
  overallUptimeTitle: Uptime complessivo
  averageResponseTime: "Tempo di risposta medio: $TIMEms"
  averageResponseTimeTitle: Tempo di risposta
  sevelDayResponseTime: Tempo di risposta a 7 giorni
  responseTimeMs: Tempo di risposta (ms)
  up: Up
  down: Down
  degraded: Degraded
  loading: Caricamento
  footer: Made with ☕ and [OSS]($REPO) by [GG](https://giovannigardin.com)
