owner: ggardin
repo: uptime-monitor
sites:
  - name: Giovanni Gardin
    url: https://www.giovannigardin.com
  - name: Ristorante Gelateria All'Angelo Da Lalo
    url: $SITE_RSTRLL
  - name: Life
    url: $SITE_LF
  - name: Life CRM
    url: $SITE_LFCRM
  - name: Barchessa Loredan
    url: $SITE_BRKLRD
  - name: Confraternita Vini Asolo Montello
    url: $SITE_CVAM
  - name: Contemporanea
    url: $SITE_CNTM
  - name: Contemporanea B2B
    url: $SITE_CNTMB
  - name: Contemporanea Group
    url: $SITE_CNTMG
  - name: Montello Country House
    url: $SITE_MCH
  - name: ProSetup
    url: $SITE_PRSTP
  - name: Sikrea
    url: $SITE_SKR
  - name: UNIPav
    url: $SITE_NPVBRT
  - name: Ekphrasis
    url: $SITE_KPHRS
  - name: Itaca Gallery
    url: $SITE_TCGLR
  - name: Punto Infissi
    url: $SITE_PTNFS
  - name: Liquorificio Benedetti
    url: $SITE_BNDTLQ

assignees:
  - ggardin

status-website:
  cname: status.giovannigardin.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Giovanni Gardin
  introTitle: "**Stato** dei servizi web"
  introMessage: Vengono impiegate numerose tecnologie di ridondanza per garantire prestazioni e affidabilità ottimali. Tuttavia, qualora compaia un problema tecnico, pensiamo che i nostri clienti meritino una comunicazione chiara e trasparente. Su questa pagina è disponibile il monitoraggio dello stato dei servizi web.
  navbar:
    - title: Status
      href: /
  themeUrl: light
  metaTags:
    - name: "theme-color"
      content: "#111417"
