# Create an issue to create an Upptime scheduled maintenance window.

name: Add scheduled maintenance

on:
  workflow_dispatch:
    inputs:
      expectedDown:
        description: 'Website expected to be down'     
        required: true
        default: 'giovanni-gardin' 
        type: choice
        options:
        - giovanni-gardin
        - ristorante-gelateria-all-angelo-da-lalo
        - life
        - life-crm
        - barchessa-loredan
        - confraternita-vini-asolo-montello
        - contemporanea
        - contemporanea-b2b
        - contemporanea-group
        - montello-country-house
        - prosetup
        - sikrea
        - unipav
        - ekphrasis
        - itaca-gallery
        - punto-infissi
        - liquorificio-benedetti
        - fabio-favrin-portfolio
      timeStart:
        description: 'Start date and time'
        default: '2022-05-03T16:00:00'
        required: true
        type: string
      timeEnd:
        description: 'End date and time'
        default: '2022-05-03T19:00:00'
        required: true
        type: string
      serverProvider:
        description: 'Provider'
        required: false
        type: string
      reason:
        description: 'Message from provider'
        required: false
        type: string

jobs:
  create-issue:
    name: Create maintenance issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "ggardin"
          labels: "maintenance"
          title: Website maintenance
          body: |-
            <!--
            start: 2022-05-03T16:00:00
            end: 2022-05-03T19:00:00
            expectedDown: giovanni-gardin
            -->
